---
# tasks file for nxrm3-api-repository-create

- debug:
    msg: "nxrm3 data is {{ nxrm3_data }}"

- name: Creating {{ nxrm3_data.name }}
  uri:
    url: "{{ nxrm3_item.host }}:{{ nxrm3_item.port }}/{{ nxrm3_api }}"
    user: "{{ nxrm3_item.user }}"
    password: "{{ nxrm3_item.passwd }}"
    headers:
        Content-Type: "application/json"
    method: POST
    status_code: 200,201,204
    force_basic_auth: yes
    body: "{{ nxrm3_data }}"
  loop: "{{ nxrm3_instances }}"
  loop_control:
    loop_var: nxrm3_item
  register: op
    
- debug:
    var: op
    

