---
- hosts: all
  vars:
    nxrm3_repo_format: "maven"
    nxrm3_repo_type: "proxy"
  tasks:
    - name: get stuff
      include_vars:
        file: ../bin/data/maven-proxy.json
        name: nxrm3_data
        
    - name: display include_vars
      debug: msg="{{ nxrm3_data }}"

    - name: Creating
      uri:
        url: "http://localhost:8081/service/rest/beta/repositories/{{ nxrm3_repo_format }}/{{ nxrm3_repo_type }}"
        user: "admin"
        password: "admin123"
        headers:
            Content-Type: "application/json"
            Accept: "application/json"
        method: POST
        status_code: 200,201,204
        force_basic_auth: yes
        body_format: json
        body: "{{ nxrm3_data }}"
      register: op
        
    - debug:
        var: op
        
    
    
      
  # roles:
  #   - { role: nxrm3-api-repository-create, nxrm3_data: "{{ nxrm3_data }}", nxrm3_api: "{{ nxrm3_repository_api }}", nxrm3_repo_format: 'maven', nxrm3_repo_type: 'proxy'}
      


