---
- hosts: all
  tasks:
    - name: get repository data
      include_vars:
        file: "{{ nxrm3_data_file }}"
        name: nxrm3_data
        
    - name: display repository info
      debug: msg="{{ nxrm3_data }}"

    - name: Creating repository {{ nxrm3_data.name }}
      uri:
        url: "{{ nxrm3_item.host }}:{{ nxrm3_item.port }}/{{ nxrm3_repository_api }}/{{ nxrm3_repo_format }}/{{ nxrm3_repo_type }}"
        user: "{{ nxrm3_item.user }}"
        password: "{{ nxrm3_item.passwd }}"
        headers:
            Content-Type: "application/json"
            Accept: "application/json"
        method: POST
        status_code: 200,201,204
        force_basic_auth: yes
        body_format: json
        body: "{{ nxrm3_data }}"
      loop: "{{ nxrm3_instances }}"
      loop_control:
        loop_var: nxrm3_item
      register: op
        
    - debug:
        var: op
        
